#ifndef COMMANDS_H
#define COMMANDS_H

typedef enum
{
  COMMAND_NONE,
  COMMAND_SELECT,
  COMMAND_ACCELERATE,
  COMMAND_SLOWDOWN,
  COMMAND_UP,
  COMMAND_DOWN,
  COMMAND_LEFT,
  COMMAND_RIGHT,
  COMMAND_UP_LEFT,
  COMMAND_DOWN_LEFT,
  COMMAND_UP_RIGHT,
  COMMAND_DOWN_RIGHT
} GameCommand;

#endif