name: Build CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up the environment
      run: |
        sudo apt update
        sudo apt install -y \
          build-essential \
          git \
          wget \
          curl \
          unzip \
          python3 \
          python3-pip \
          libtool \
          autoconf \
          pkg-config

    - name: Install libdragon
      run: |
        git clone https://github.com/DragonMinded/libdragon.git
        cd libdragon
        make

    - name: Build project
      run: |
        make
